### ISSUE TITLE
Performance improvement better?

### ISSUE THREAD

**Issue by np28** [DenitS/yii-apiAuth#10]
Would it not be better to move 
    Yii::app()->apiAuth 
from AController::init() to AController::filterApiAuth().

So you can prevent, that the component is created, if it is only configured for some actions of a controller in filters().

**Comment by DenitS** [comment]
You're probably right. The effect should be minimal, but it does prevent unnessary instantiation in those cases. Would you like to change it, test if it doesn't cause problems and issue a pull request?
